create table if not exists public.videos (
  id text primary key default gen_random_uuid()::text,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  tags text[] not null default '{}',
  video_url text not null,
  poster_url text,
  product_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.video_likes (
  video_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create table if not exists public.video_comments (
  id uuid primary key default gen_random_uuid(),
  video_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  user_name text not null,
  user_avatar text not null,
  created_at timestamptz not null default now()
);

alter table public.videos enable row level security;
alter table public.video_likes enable row level security;
alter table public.video_comments enable row level security;

create policy "Public videos are readable" on public.videos for select using (true);
create policy "Users can publish their own videos" on public.videos for insert with check (auth.uid() = creator_id);
create policy "Users can delete their own videos" on public.videos for delete using (auth.uid() = creator_id);

create policy "Public likes are readable" on public.video_likes for select using (true);
create policy "Users can like as themselves" on public.video_likes for insert with check (auth.uid() = user_id);
create policy "Users can remove their own likes" on public.video_likes for delete using (auth.uid() = user_id);

create policy "Public comments are readable" on public.video_comments for select using (true);
create policy "Users can comment as themselves" on public.video_comments for insert with check (auth.uid() = user_id);
create policy "Users can delete their own comments" on public.video_comments for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('videos', 'videos', true)
on conflict (id) do nothing;

create policy "Public video files are readable" on storage.objects for select using (bucket_id = 'videos');
create policy "Users can upload video files" on storage.objects for insert with check (bucket_id = 'videos' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "Users can delete their video files" on storage.objects for delete using (bucket_id = 'videos' and auth.uid()::text = (storage.foldername(name))[1]);

alter table public.video_likes replica identity full;
alter table public.video_comments replica identity full;
alter publication supabase_realtime add table public.video_likes;
alter publication supabase_realtime add table public.video_comments;

-- Marketplace configuration and Pakistan fulfilment rules.
create table if not exists public.system_settings (
  key text primary key,
  value numeric not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.system_settings (key, value)
values ('pakistan_platform_commission_percent', 5)
on conflict (key) do nothing;

create table if not exists public.delivery_matrix (
  id bigint generated by default as identity primary key,
  zone text not null check (zone in ('same-city', 'major-intercity', 'remote')),
  base_weight_kg numeric not null default 1,
  base_rate_pkr integer not null,
  additional_kg_rate_pkr integer not null default 60,
  remote_surcharge_pkr integer not null default 0,
  active boolean not null default true,
  unique (zone, base_weight_kg)
);

insert into public.delivery_matrix (zone, base_weight_kg, base_rate_pkr, additional_kg_rate_pkr, remote_surcharge_pkr)
values
  ('same-city', 1, 160, 60, 0),
  ('major-intercity', 1, 200, 60, 0),
  ('remote', 1, 200, 60, 50)
on conflict (zone, base_weight_kg) do nothing;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  tracking_id text not null unique,
  buyer_id uuid not null references auth.users(id),
  seller_id uuid references auth.users(id),
  subtotal_pkr integer not null,
  delivery_fee_pkr integer not null,
  discount_pkr integer not null default 0,
  total_pkr integer not null,
  platform_commission_percent numeric not null default 5,
  platform_fee_pkr integer not null default 0,
  seller_payout_pkr integer not null default 0,
  delivery_zone text not null check (delivery_zone in ('same-city', 'major-intercity', 'remote')),
  package_weight_kg numeric not null default 1,
  fulfillment_method text not null default 'doorstep' check (fulfillment_method = 'doorstep'),
  delivered_at timestamptz,
  return_claim_deadline timestamptz,
  settlement_available_at timestamptz,
  settlement_status text not null default 'escrow' check (settlement_status in ('escrow', 'processing-settlement', 'available', 'refunded')),
  customer_name text not null,
  customer_phone text not null,
  customer_city text not null,
  customer_address text not null,
  notes text,
  payment_method text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  seller_id uuid references auth.users(id),
  quantity integer not null check (quantity > 0),
  unit_price_pkr integer not null,
  line_total_pkr integer not null
);

create table if not exists public.seller_wallets (
  seller_id uuid primary key references auth.users(id) on delete cascade,
  escrow_pkr integer not null default 0,
  processing_settlement_pkr integer not null default 0,
  available_balance_pkr integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_ledger (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references auth.users(id),
  order_id uuid references public.orders(id),
  amount_pkr integer not null,
  category text not null check (category in ('escrow', 'processing-settlement', 'available', 'commission', 'payout', 'refund')),
  available_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id uuid not null references public.orders(id),
  rating integer not null check (rating between 1 and 5),
  body text not null check (char_length(body) between 1 and 2000),
  verified_purchase boolean not null default false,
  helpful_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, user_id, order_id)
);

create table if not exists public.product_review_images (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.product_reviews(id) on delete cascade,
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.review_helpful (
  review_id uuid not null references public.product_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

alter table public.system_settings enable row level security;
alter table public.delivery_matrix enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.seller_wallets enable row level security;
alter table public.wallet_ledger enable row level security;
alter table public.product_reviews enable row level security;
alter table public.product_review_images enable row level security;
alter table public.review_helpful enable row level security;

create policy "Public delivery matrix is readable" on public.delivery_matrix for select using (active = true);
create policy "Buyers can read their orders" on public.orders for select using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "Buyers can create doorstep orders" on public.orders for insert with check (auth.uid() = buyer_id and fulfillment_method = 'doorstep');
create policy "Order participants can read items" on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and (o.buyer_id = auth.uid() or o.seller_id = auth.uid())));
create policy "Sellers can read their wallet" on public.seller_wallets for select using (auth.uid() = seller_id);
create policy "Sellers can read their ledger" on public.wallet_ledger for select using (auth.uid() = seller_id);
create policy "Published reviews are readable" on public.product_reviews for select using (true);
create policy "Verified buyers can publish reviews" on public.product_reviews for insert with check (auth.uid() = user_id and verified_purchase = true);
create policy "Review images are readable" on public.product_review_images for select using (true);
create policy "Review authors can add images" on public.product_review_images for insert with check (exists (select 1 from public.product_reviews r where r.id = review_id and r.user_id = auth.uid() and r.verified_purchase = true));
create policy "Helpful votes are readable" on public.review_helpful for select using (true);
create policy "Users can vote helpful once" on public.review_helpful for insert with check (auth.uid() = user_id);
create policy "Users can remove helpful vote" on public.review_helpful for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('review-images', 'review-images', true)
on conflict (id) do nothing;

create policy "Public review images are readable" on storage.objects for select using (bucket_id = 'review-images');
create policy "Verified buyers can upload review images" on storage.objects for insert with check (bucket_id = 'review-images' and auth.uid() is not null);

create or replace function public.calculate_order_commission(gross_pkr integer)
returns table (commission_percent numeric, platform_fee_pkr integer, seller_payout_pkr integer)
language sql stable security definer set search_path = public
as $$
  select s.value, round(gross_pkr * s.value / 100)::integer, gross_pkr - round(gross_pkr * s.value / 100)::integer
  from public.system_settings s
  where s.key = 'pakistan_platform_commission_percent';
$$;

create or replace function public.apply_order_financials()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare commission_rate numeric;
begin
  select value into commission_rate from public.system_settings where key = 'pakistan_platform_commission_percent';
  new.platform_commission_percent := coalesce(commission_rate, 5);
  new.platform_fee_pkr := round(new.subtotal_pkr * new.platform_commission_percent / 100)::integer;
  new.seller_payout_pkr := greatest(0, new.subtotal_pkr - new.platform_fee_pkr);
  new.fulfillment_method := 'doorstep';
  new.settlement_status := 'escrow';
  return new;
end;
$$;

drop trigger if exists order_financials_before_insert on public.orders;
create trigger order_financials_before_insert
before insert on public.orders
for each row execute function public.apply_order_financials();

create or replace function public.advance_due_settlements()
returns void
language plpgsql security definer set search_path = public
as $$
begin
  update public.orders
  set settlement_status = 'processing-settlement'
  where delivered_at is not null
    and delivered_at <= now() - interval '9 days'
    and settlement_status = 'escrow';

  update public.orders
  set settlement_status = 'available'
  where delivered_at is not null
    and delivered_at <= now() - interval '13 days'
    and settlement_status = 'processing-settlement';
end;
$$;
